language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script:
  - cd src
script:
  - mvn clean test -Prelease -B -T2
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master

