sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script:
  - cd src
script:
  - mvn -B -U -T2 -fae -Prelease clean install
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
